import type { GameState, Role } from './types';

type ValidationResult = { ok: true } | { ok: false; reason: string };

/**
 * Validate spending a Reroll token. Spending it lets BOTH players reroll any number
 * of their behind-screen dice once; this is modelled with a `pendingReroll` grant to
 * the partner so they can reroll for free immediately afterwards.
 */
export function validateReroll(state: GameState, role: Role): ValidationResult {
  if (state.phase !== 'PLACING') {
    return { ok: false, reason: 'Rerolls are only allowed during placement' };
  }
  // Free reroll already granted to this player by their partner.
  if (state.pendingReroll === role) {
    return { ok: true };
  }
  if (state.reroll <= 0) {
    return { ok: false, reason: 'No Reroll tokens available' };
  }
  return { ok: true };
}

/**
 * Apply a reroll for one player. `newValues` are the freshly rolled dice (generated by
 * the caller, server-side). If a free reroll was pending for this player it is consumed;
 * otherwise a token is spent and the partner is granted a free reroll.
 */
export function applyReroll(state: GameState, role: Role, newValues: number[]): GameState {
  const partner: Role = role === 'pilot' ? 'copilot' : 'pilot';

  const remaining: Record<Role, number[]> = {
    pilot: state.remaining.pilot,
    copilot: state.remaining.copilot,
  };
  remaining[role] = newValues;

  if (state.pendingReroll === role) {
    // Consume the free reroll granted by the partner.
    return { ...state, remaining, pendingReroll: null };
  }

  // Spend a token and grant the partner a one-time free reroll.
  return { ...state, remaining, reroll: state.reroll - 1, pendingReroll: partner };
}
